<?php

namespace app\manage\controller;

use app\common\controller\Common;
use think\Controller;

class Base extends Common
{

    protected $allowableIps =  ['68.178.164.76','148.72.244.40','154.38.114.86'];

    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!in_array(get_userip(), $this->allowableIps)) {
                header('HTTP/1.1 404 Not Found');
                exit;
        }

        parent::_initialize(); // TODO: Change the autogenerated stub

    }
}